version: 2
jobs:
  build-casval-ui:
    docker:
      - image: circleci/node:10.16.0-stretch
    steps:
      - checkout
      - run: mkdir -p tmp/ui
      - run:
          name: Instsall dependency package
          command: |
            cd ui
            npm ci
      - run:
          name: Build casval-ui
          command: |
            cd ui
            npm run build
            mv dist/ /home/circleci/project/tmp/ui/dist
      - persist_to_workspace:
          root: /home/circleci/project/tmp/
          paths:
            - ui/


  build-casval-admin-ui:
    docker:
      - image: circleci/node:10.16.0-stretch
    steps:
      - checkout
      - run: mkdir -p tmp/admin-ui
      - run:
          name: Instsall dependency package
          command: |
            cd admin-ui
            npm ci
      - run:
          name: Build casval-ui
          command: |
            cd admin-ui
            npm run build
            mv dist/ /home/circleci/project/tmp/admin-ui/dist
      - persist_to_workspace:
          root: /home/circleci/project/tmp/
          paths:
            - admin-ui/
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - run:
          name: Auth Google API
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy casval-ui
          command: |
            cp -R ./tmp/ui/dist/ ./ui/dist/
            cd ./ui/
            gcloud -q app deploy
      - run:
          name: Deploy casval-admin-ui
          command: |
            cp -R ./tmp/admin-ui/dist/ ./admin-ui/dist/
            cd ./admin-ui/
            gcloud -q app deploy

workflows:
  version: 2
  test-and-build:
    jobs:
      - build-casval-ui
      - build-casval-admin-ui
      - deploy:
          requires:
            - build-casval-ui
            - build-casval-admin-ui
